# Generated by Django 2.2.12 on 2021-04-14 02:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ClockWorkApp', '0002_profile_timezone'),
    ]

    operations = [
        migrations.AddField(
            model_name='week',
            name='goal',
            field=models.PositiveSmallIntegerField(default=0),
        ),
    ]
