# Generated by Django 2.2.12 on 2021-04-16 17:24

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ClockWorkApp', '0003_week_goal'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='day_end_time',
            field=models.CharField(choices=[(0, '12am'), (1, '1am'), (2, '2am'), (3, '3am'), (4, '4am'), (5, '5am'), (6, '6am'), (7, '7am'), (8, '8am'), (9, '9am'), (10, '10am'), (11, '11am'), (12, '12pm'), (13, '1pm'), (14, '2pm'), (15, '3pm'), (16, '4pm'), (17, '5pm'), (18, '6pm'), (19, '7pm'), (20, '8pm'), (21, '9pm'), (22, '10pm'), (23, '11pm')], default='10pm', max_length=4),
        ),
        migrations.AddField(
            model_name='profile',
            name='day_start_time',
            field=models.CharField(choices=[(0, '12am'), (1, '1am'), (2, '2am'), (3, '3am'), (4, '4am'), (5, '5am'), (6, '6am'), (7, '7am'), (8, '8am'), (9, '9am'), (10, '10am'), (11, '11am'), (12, '12pm'), (13, '1pm'), (14, '2pm'), (15, '3pm'), (16, '4pm'), (17, '5pm'), (18, '6pm'), (19, '7pm'), (20, '8pm'), (21, '9pm'), (22, '10pm'), (23, '11pm')], default='5am', max_length=4),
        ),
        migrations.AlterField(
            model_name='week',
            name='goal',
            field=models.PositiveSmallIntegerField(default=40, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(168)]),
        ),
    ]
