# Generated by Django 2.2.12 on 2021-04-16 17:28

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ClockWorkApp', '0004_auto_20210416_1724'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='default_goal',
            field=models.PositiveSmallIntegerField(default=40, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(168)]),
        ),
    ]
